export const provincias = [
    { value: 'Buenos_Aires', label: 'Buenos Aires' },
    { value: 'CABA', label: 'Ciudad Autónoma de Buenos Aires' },
    { value: 'Catamarca', label: 'Catamarca' },
    { value: 'Chaco', label: 'Chaco' },
    { value: 'Chubut', label: 'Chubut' },
    { value: 'Cordoba', label: 'Córdoba' },
    { value: 'Corrientes', label: 'Corrientes' },
    { value: 'Entre_Rios', label: 'Entre Ríos' },
    { value: 'Formosa', label: 'Formosa' },
    { value: 'Jujuy', label: 'Jujuy' },
    { value: 'La_Pampa', label: 'La Pampa' },
    { value: 'La_Rioja', label: 'La Rioja' },
    { value: 'Mendoza', label: 'Mendoza' },
    { value: 'Misiones', label: 'Misiones' },
    { value: 'Neuquen', label: 'Neuquén' },
    { value: 'Rio_Negro', label: 'Río Negro' },
    { value: 'Salta', label: 'Salta' },
    { value: 'San_Juan', label: 'San Juan' },
    { value: 'San_Luis', label: 'San Luis' },
    { value: 'Santa_Cruz', label: 'Santa Cruz' },
    { value: 'Santa_Fe', label: 'Santa Fe' },
    { value: 'Santiago_del_Estero', label: 'Santiago del Estero' },
    { value: 'Tierra_del_Fuego', label: 'Tierra del Fuego' },
    { value: 'Tucuman', label: 'Tucumán' },
];
